apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-go-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-go-app
  template:
    metadata:
      labels:
        app: grpc-go-app
    spec:
      containers:
      - name: grpc-go-app
        image: rahul0409/totality-assignment:01
