apiVersion: v1
kind: Service
metadata:
  name: service-grpc-go-app
spec:
  selector:
    app.kubernetes.io/name: grpc-go-app
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer